CREATE schema OMOCDM54BACKUP;
SELECT
  'CREATE TABLE OMOPCDM54BACKUP.' || TABLE_NAME ||
  ' AS SELECT * FROM OMOPCDM54.' || TABLE_NAME || ';' AS ddl
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'OMOPCDM54'
  AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;